import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Uguumur - Teacher</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="dark:bg-gray-800 bg-slate-100 h-screen w-screen flex justify-center items-center">
        <div className="w-80 h-60 bg-slate-100 rounded-md shadow-lg">
          Uguumur
        </div>
      </div>
    </>
  );
}
