import Header from "../components/header";
import Head from "next/head";
import { useState } from "react";
import { toast } from "react-toastify";

export default function Plan() {
  const [data, setData] = useState([
    {
      name: "NextJS",
      price: "1000$",
    },
    {
      name: "Tailwind",
      price: "1000$",
    },
    {
      name: "Python data science",
      price: "1000$",
    },
    {
      name: "Database",
      price: "1000$",
    },
  ]);

  const [count, setCount] = useState(0);

  return (
    <>
      <Head>
        <title>Сургалт</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header count={count} clearCount={() => setCount(0)} />

      <div className="h-full w-full mt-8 px-8 gap-4 dark:bg-gray-800 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
        {data.map((row, i) => (
          <div
            key={i}
            className="w-full h-72 bg-slate-100 rounded-md pt-4 px-4 shadow-lg border-2 border-cyan-400 dark:border-green-200 dark:bg-gray-800 dark:text-slate-200"
          >
            <div className="font-bold text-xl">{row.name}</div>
            <div className="font-bold text-red-500">{row.price}</div>
            <button
              onClick={() => {
                toast.success("Бараа нэмэгдлээ");
                setCount(count + 1);
              }}
              className="bg-cyan-400 flex px-2 py-1 gap-1 rounded"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                viewBox="0 0 24 24"
                fill="currentColor"
                className="w-6 h-6"
              >
                <path d="M2.25 2.25a.75.75 0 000 1.5h1.386c.17 0 .318.114.362.278l2.558 9.592a3.752 3.752 0 00-2.806 3.63c0 .414.336.75.75.75h15.75a.75.75 0 000-1.5H5.378A2.25 2.25 0 017.5 15h11.218a.75.75 0 00.674-.421 60.358 60.358 0 002.96-7.228.75.75 0 00-.525-.965A60.864 60.864 0 005.68 4.509l-.232-.867A1.875 1.875 0 003.636 2.25H2.25zM3.75 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0zM16.5 20.25a1.5 1.5 0 113 0 1.5 1.5 0 01-3 0z" />
              </svg>
              Сагсанд нэмэх
            </button>
          </div>
        ))}
      </div>

      <div className="w-full"></div>
    </>
  );
}
