import Header from "../components/header";
import Head from "next/head";

export default function Plan() {
  return (
    <>
      <Head>
        <title>Сургалт</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="h-screen w-full dark:bg-gray-800 grid grid-cols-2 md:grid-cols-3 lg:grid-cols-5">
        <div className="w-full h-72 bg-slate-300 shadow-lg border-2 border-cyan-400"></div>
        <div className="w-full h-72 bg-slate-300 shadow-lg border-2 border-cyan-400"></div>
        <div className="w-full h-72 bg-slate-300 shadow-lg border-2 border-cyan-400"></div>
        <div className="w-full h-72 bg-slate-300 shadow-lg border-2 border-cyan-400"></div>
        <div className="w-full h-72 bg-slate-300 shadow-lg border-2 border-cyan-400"></div>
        <div className="w-full h-72 bg-slate-300 shadow-lg border-2 border-cyan-400"></div>
      </div>
    </>
  );
}
